
#(testqt) D:\MyWork\Tools\Annotation_Tool\window>python D:\Software\Anaconda\envs\testqt\Library\bin\pyside2-uic mainwindow.ui 
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Tue Jun  4 15:43:11 2019
#      by: pyside2-uic 2.0.0 running on PySide2 5.6.0~a1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1240, 842)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setMaximumSize(QtCore.QSize(214, 16777215))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea_categories = QtWidgets.QScrollArea(self.groupBox)
        self.scrollArea_categories.setWidgetResizable(True)
        self.scrollArea_categories.setObjectName("scrollArea_categories")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 192, 419))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableWidget_categories = QtWidgets.QTableWidget(self.scrollAreaWidgetContents_2)
        self.tableWidget_categories.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.tableWidget_categories.setAlternatingRowColors(True)
        self.tableWidget_categories.setTextElideMode(QtCore.Qt.ElideLeft)
        self.tableWidget_categories.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_categories.setObjectName("tableWidget_categories")
        self.tableWidget_categories.setColumnCount(0)
        self.tableWidget_categories.setRowCount(0)
        self.tableWidget_categories.horizontalHeader().setVisible(False)
        self.tableWidget_categories.horizontalHeader().setDefaultSectionSize(130)
        self.tableWidget_categories.horizontalHeader().setMinimumSectionSize(20)
        self.tableWidget_categories.verticalHeader().setVisible(True)
        self.verticalLayout_2.addWidget(self.tableWidget_categories)
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 120))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_applyCategory = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_applyCategory.setObjectName("btn_applyCategory")
        self.verticalLayout_3.addWidget(self.btn_applyCategory)
        self.btn_chooseColor = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_chooseColor.setObjectName("btn_chooseColor")
        self.verticalLayout_3.addWidget(self.btn_chooseColor)
        self.btn_addCategory = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_addCategory.setObjectName("btn_addCategory")
        self.verticalLayout_3.addWidget(self.btn_addCategory)
        self.btn_deleteCategory = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_deleteCategory.setObjectName("btn_deleteCategory")
        self.verticalLayout_3.addWidget(self.btn_deleteCategory)
        self.btn_refresh = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_refresh.setObjectName("btn_refresh")
        self.verticalLayout_3.addWidget(self.btn_refresh)
        self.btn_saveCategory = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_saveCategory.setObjectName("btn_saveCategory")
        self.verticalLayout_3.addWidget(self.btn_saveCategory)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.scrollArea_categories.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout.addWidget(self.scrollArea_categories)
        self.setting_area = QtWidgets.QGroupBox(self.groupBox)
        self.setting_area.setMinimumSize(QtCore.QSize(0, 230))
        self.setting_area.setTitle("")
        self.setting_area.setObjectName("setting_area")
        self.label_startFrame = QtWidgets.QLabel(self.setting_area)
        self.label_startFrame.setGeometry(QtCore.QRect(10, 10, 81, 31))
        self.label_startFrame.setObjectName("label_startFrame")
        self.label_frameStep = QtWidgets.QLabel(self.setting_area)
        self.label_frameStep.setGeometry(QtCore.QRect(10, 40, 81, 31))
        self.label_frameStep.setObjectName("label_frameStep")
        self.label_totalFrames = QtWidgets.QLabel(self.setting_area)
        self.label_totalFrames.setGeometry(QtCore.QRect(10, 120, 81, 31))
        self.label_totalFrames.setObjectName("label_totalFrames")
        self.label_totalFrames_2 = QtWidgets.QLabel(self.setting_area)
        self.label_totalFrames_2.setGeometry(QtCore.QRect(100, 120, 81, 31))
        self.label_totalFrames_2.setObjectName("label_totalFrames_2")
        self.label_currentFrame = QtWidgets.QLabel(self.setting_area)
        self.label_currentFrame.setGeometry(QtCore.QRect(10, 150, 81, 31))
        self.label_currentFrame.setObjectName("label_currentFrame")
        self.label_currentFrame_2 = QtWidgets.QLabel(self.setting_area)
        self.label_currentFrame_2.setGeometry(QtCore.QRect(100, 150, 81, 31))
        self.label_currentFrame_2.setObjectName("label_currentFrame_2")
        self.btn_applySetting = QtWidgets.QPushButton(self.setting_area)
        self.btn_applySetting.setGeometry(QtCore.QRect(60, 190, 75, 23))
        self.btn_applySetting.setObjectName("btn_applySetting")
        self.plainTextEdit_startFrame = QtWidgets.QPlainTextEdit(self.setting_area)
        self.plainTextEdit_startFrame.setGeometry(QtCore.QRect(100, 10, 81, 21))
        self.plainTextEdit_startFrame.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_startFrame.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_startFrame.setObjectName("plainTextEdit_startFrame")
        self.plainTextEdit_frameStep = QtWidgets.QPlainTextEdit(self.setting_area)
        self.plainTextEdit_frameStep.setGeometry(QtCore.QRect(100, 50, 81, 21))
        self.plainTextEdit_frameStep.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_frameStep.setObjectName("plainTextEdit_frameStep")
        self.verticalLayout.addWidget(self.setting_area)
        self.gridLayout.addWidget(self.groupBox, 0, 1, 1, 1)
        self.groupbox_buttons = QtWidgets.QGroupBox(self.centralWidget)
        self.groupbox_buttons.setMinimumSize(QtCore.QSize(1002, 100))
        self.groupbox_buttons.setMaximumSize(QtCore.QSize(16777215, 100))
        self.groupbox_buttons.setTitle("")
        self.groupbox_buttons.setObjectName("groupbox_buttons")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupbox_buttons)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textEdit_statusBar = QtWidgets.QTextEdit(self.groupbox_buttons)
        self.textEdit_statusBar.setReadOnly(True)
        self.textEdit_statusBar.setObjectName("textEdit_statusBar")
        self.horizontalLayout.addWidget(self.textEdit_statusBar)
        self.stackedWidget = QtWidgets.QStackedWidget(self.groupbox_buttons)
        self.stackedWidget.setMinimumSize(QtCore.QSize(630, 80))
        self.stackedWidget.setMaximumSize(QtCore.QSize(630, 80))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.btn_next = QtWidgets.QPushButton(self.page)
        self.btn_next.setGeometry(QtCore.QRect(110, 30, 75, 23))
        self.btn_next.setObjectName("btn_next")
        self.btn_back = QtWidgets.QPushButton(self.page)
        self.btn_back.setGeometry(QtCore.QRect(20, 30, 75, 23))
        self.btn_back.setObjectName("btn_back")
        self.btn_save = QtWidgets.QPushButton(self.page)
        self.btn_save.setGeometry(QtCore.QRect(200, 30, 75, 23))
        self.btn_save.setObjectName("btn_save")
        self.btn_deleteSelected = QtWidgets.QPushButton(self.page)
        self.btn_deleteSelected.setGeometry(QtCore.QRect(290, 30, 111, 23))
        self.btn_deleteSelected.setObjectName("btn_deleteSelected")
        self.btn_deleteUnsaved = QtWidgets.QPushButton(self.page)
        self.btn_deleteUnsaved.setGeometry(QtCore.QRect(420, 30, 91, 23))
        self.btn_deleteUnsaved.setObjectName("btn_deleteUnsaved")
        self.btn_deleteAll = QtWidgets.QPushButton(self.page)
        self.btn_deleteAll.setGeometry(QtCore.QRect(530, 30, 75, 23))
        self.btn_deleteAll.setObjectName("btn_deleteAll")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.horizontalLayout.addWidget(self.stackedWidget)
        self.gridLayout.addWidget(self.groupbox_buttons, 1, 0, 1, 2)
        self.img_area = QtWidgets.QLabel(self.centralWidget)
        self.img_area.setEnabled(True)
        self.img_area.setMinimumSize(QtCore.QSize(1002, 587))
        self.img_area.setFrameShape(QtWidgets.QFrame.Box)
        self.img_area.setText("")
        self.img_area.setObjectName("img_area")
        self.gridLayout.addWidget(self.img_area, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1240, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuLabeling_for_Yolo = QtWidgets.QMenu(self.menuBar)
        self.menuLabeling_for_Yolo.setGeometry(QtCore.QRect(-1621, 100, 176, 94))
        self.menuLabeling_for_Yolo.setObjectName("menuLabeling_for_Yolo")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.act_openfile = QtWidgets.QAction(MainWindow)
        self.act_openfile.setObjectName("act_openfile")
        self.act_opendir = QtWidgets.QAction(MainWindow)
        self.act_opendir.setObjectName("act_opendir")
        self.actions = QtWidgets.QAction(MainWindow)
        self.actions.setObjectName("actions")
        self.act_openUsage = QtWidgets.QAction(MainWindow)
        self.act_openUsage.setObjectName("act_openUsage")
        self.menuLabeling_for_Yolo.addAction(self.act_openfile)
        self.menuLabeling_for_Yolo.addAction(self.act_opendir)
        self.menuHelp.addAction(self.act_openUsage)
        self.menuBar.addAction(self.menuLabeling_for_Yolo.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.btn_applyCategory.setText(QtWidgets.QApplication.translate("MainWindow", "Apply Category (E)", None, -1))
        self.btn_chooseColor.setText(QtWidgets.QApplication.translate("MainWindow", "Choose Color", None, -1))
        self.btn_addCategory.setText(QtWidgets.QApplication.translate("MainWindow", "Add Category", None, -1))
        self.btn_deleteCategory.setText(QtWidgets.QApplication.translate("MainWindow", "Delete Category", None, -1))
        self.btn_refresh.setText(QtWidgets.QApplication.translate("MainWindow", "Refresh", None, -1))
        self.btn_saveCategory.setText(QtWidgets.QApplication.translate("MainWindow", "Save to file", None, -1))
        self.label_startFrame.setText(QtWidgets.QApplication.translate("MainWindow", "Start Frame", None, -1))
        self.label_frameStep.setText(QtWidgets.QApplication.translate("MainWindow", "Frame Step", None, -1))
        self.label_totalFrames.setText(QtWidgets.QApplication.translate("MainWindow", "Total Frames", None, -1))
        self.label_totalFrames_2.setText(QtWidgets.QApplication.translate("MainWindow", "N.A.", None, -1))
        self.label_currentFrame.setText(QtWidgets.QApplication.translate("MainWindow", "Current Frame", None, -1))
        self.label_currentFrame_2.setText(QtWidgets.QApplication.translate("MainWindow", "N.A.", None, -1))
        self.btn_applySetting.setText(QtWidgets.QApplication.translate("MainWindow", "Apply", None, -1))
        self.btn_next.setText(QtWidgets.QApplication.translate("MainWindow", "Next (N)", None, -1))
        self.btn_back.setText(QtWidgets.QApplication.translate("MainWindow", "Back (B)", None, -1))
        self.btn_save.setText(QtWidgets.QApplication.translate("MainWindow", "Save (S)", None, -1))
        self.btn_deleteSelected.setText(QtWidgets.QApplication.translate("MainWindow", "Delete Selected (D)", None, -1))
        self.btn_deleteUnsaved.setText(QtWidgets.QApplication.translate("MainWindow", "Delete Unsaved", None, -1))
        self.btn_deleteAll.setText(QtWidgets.QApplication.translate("MainWindow", "Delete All", None, -1))
        self.menuLabeling_for_Yolo.setTitle(QtWidgets.QApplication.translate("MainWindow", "File", None, -1))
        self.menuHelp.setTitle(QtWidgets.QApplication.translate("MainWindow", "Help", None, -1))
        self.act_openfile.setText(QtWidgets.QApplication.translate("MainWindow", "Open Video", None, -1))
        self.act_opendir.setText(QtWidgets.QApplication.translate("MainWindow", "Open Image Directory", None, -1))
        self.actions.setText(QtWidgets.QApplication.translate("MainWindow", "s", None, -1))
        self.act_openUsage.setText(QtWidgets.QApplication.translate("MainWindow", "Open Usage", None, -1))

